services:
  nginx:
    image: nginx:latest
    container_name: nginx_mystique
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx/conf
    networks:
      - backend
  postgres:
    image: postgres:latest
    container_name: postgres_mystique
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mystique_aura
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - backend
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_mystique
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    networks:
      - backend
    depends_on:
      - postgres
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq_mystique
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend

volumes:
  postgres_data:
  pgadmin_data:

networks:
  backend:
    driver: bridge